name: Build and deploy front
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.autoboyarin.site
          username: svc_autoboyarin
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: registry.autoboyarin.site/autoboyarin/working-scheduler:latest,registry.autoboyarin.site/autoboyarin/working-scheduler:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install helm3
        run: sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Pass envs to values file
        run: envsubst < deploy/prod.yml > deploy/prod.yml.filled
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_TAG: ${{ github.sha }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}

      - name: Add helm repo
        run: |
          helm repo add autoboyarin \
            https://nexus.autoboyarin.site/repository/autoboyarin-helm/ \
            --username svc_autoboyarin \
            --password $HELM_PASSWORD
        env:
          HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}

      - name: Prepare kubeconfig
        run: |
          echo $KUBECONFIG | base64 -d > .kubeconfig
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"

      - name: Run deploy
        run: |
          helm upgrade \
            -i working-scheduler autoboyarin/autoboyarin-timeweb-universal \
            -f deploy/prod.yml.filled \
            --version 0.1.1 \
            --namespace autoboyarin \
            --history-max 5 \
            --atomic
        env:
          KUBECONFIG: .kubeconfig